### PR TITLE
send dpid to controller

### PR DESCRIPTION
**Pull request by joncnet**

### CODE REVIEW

**Comment by rriggio** [comment]
Why is the dpid bridge different ? It should be the same of the bridge.

**Comment by joncnet** [comment]
bridge is a MAC address and it is used as the PNFDev identifier, while dpid is the 64 bit value used for the OF part

**Comment by rriggio** [comment]
ok, i think it would be better to pass the name of the bridge instead and
have the script lookup for the relevant ids.

**Comment by joncnet** [comment]
I see... the same is done for the hwaddr.
For the lvap-agent is different though I guess, in that case the agent starts with all the ids provided by the bash script

**Comment by joncnet** [comment]
Also I think that, differently from the hwaddr, for the dpid I still have to run the ovs-ofctl utility from the python agent, otherwise I would have to connect to the OvS rpc server.

**Comment by rriggio** [comment]
ok, implement it running the ofctl command.

**Pull request merged**
